insert into public.encyclopedia_entries (
  id,
  type,
  name,
  scientific_name,
  genus,
  category_code,
  category_name,
  risk_level,
  season,
  host_range,
  summary,
  morphology,
  symptoms,
  image_url,
  control_tips,
  placement_tips,
  references
)
values
  (
    'insect-myzus-persicae-1',
    'insect',
    '桃蚜',
    'Myzus persicae',
    'Myzus',
    'sapSucker',
    '刺吸式害虫',
    'high',
    '春季至初夏，秋季回升',
    '桃、辣椒、茄子、马铃薯',
    '桃蚜在春季至初夏与秋季回升期易在多种作物上暴发，属于高风险刺吸式害虫。',
    '桃蚜（Myzus persicae）刺吸式口器明显，常群集于嫩梢和叶背。',
    '受害叶片易卷曲失绿，蜜露污染后常诱发煤污。',
    '/images/encyclopedia/local/bda672ac61322aebb80e43d262913eb6.jpg',
    '["抽梢期每周巡查叶背与嫩梢。", "优先使用黄板、冲洗和天敌保育。", "必要时轮换低毒药剂并覆盖叶背。"]'::jsonb,
    '["避免高感寄主单一连片种植。", "减少偏施氮肥导致的嫩梢徒长。", "新购盆栽先隔离观察 7-10 天。"]'::jsonb,
    '["https://ipm.ucanr.edu/", "https://www.fao.org/plant-health/en/"]'::jsonb
  ),
  (
    'insect-aphis-gossypii-1',
    'insect',
    '棉蚜',
    'Aphis gossypii',
    'Aphis',
    'sapSucker',
    '刺吸式害虫',
    'high',
    '4-10 月持续发生',
    '棉花、黄瓜、茄果和观赏植物',
    '棉蚜在高温季节扩繁快，易在嫩梢和叶背形成群聚危害。',
    '棉蚜（Aphis gossypii）体型小，繁殖速率高，常伴随蜜露与煤污。',
    '受害植株叶片皱缩失绿，严重时长势受抑并诱发次生病害。',
    '/images/encyclopedia/local/13a61076116cfd3da7c4303b4d75d8b6.jpg',
    '["苗期与抽梢期定点巡查。", "优先采用黄板与冲洗压低虫口。", "必要时轮换低毒药剂并注意抗性管理。"]'::jsonb,
    '["避免偏施氮肥导致嫩梢徒长。", "清除田边寄主杂草。", "保持通风，降低群聚风险。"]'::jsonb,
    '["https://ipm.ucanr.edu/", "https://www.fao.org/plant-health/en/"]'::jsonb
  ),
  (
    'disease-erysiphe-spp-1',
    'disease',
    '白粉病',
    'Erysiphe spp.',
    'Erysiphe',
    'powdery',
    '白粉病类',
    'medium',
    '春末至秋初干湿交替期',
    '月季、黄瓜、葡萄、豆科和花卉',
    '白粉病在干湿交替环境中扩展较快，影响叶片光合能力。',
    '病部常见白色粉状霉层。',
    '叶片光合面积下降，嫩梢发育受抑。',
    'https://lh3.googleusercontent.com/aida-public/AB6AXuBzkUS5hEWFRyj4tm63W_UvLJb0yTfLOSmnk0Y7dC9-GY9HSsp6ZHo9rSscdV0JGNwSF22EYIzfCU4t7BEAuT8Vgz_8paJFBjRpZ6oXhcW_26izw_9wfbxXAoxnbo-UJZutbAO_6Hui1WwkQI0NtwvwQ39wmMe3ujQbQF7c6RnX_cD4bAMCluto2GuPFNi3FENPVWoqNPp_X5y3bctCixHTF0MGdnXA1Rhow-uEe58yR9ju5PvjZCy9tAU2p0zG4ovVtAGVMiZ0KsI',
    '["改善通风透光并减少夜间湿叶。", "及时去除病叶病梢。", "初发期轮换药剂。"]'::jsonb,
    '["花坛保持株行距。", "浇水尽量在上午。", "高感植物避免长期阴湿。"]'::jsonb,
    '["https://www.apsnet.org/", "https://www.fao.org/plant-health/en/"]'::jsonb
  )
on conflict (id) do update
set
  type = excluded.type,
  name = excluded.name,
  scientific_name = excluded.scientific_name,
  genus = excluded.genus,
  category_code = excluded.category_code,
  category_name = excluded.category_name,
  risk_level = excluded.risk_level,
  season = excluded.season,
  host_range = excluded.host_range,
  summary = excluded.summary,
  morphology = excluded.morphology,
  symptoms = excluded.symptoms,
  image_url = excluded.image_url,
  control_tips = excluded.control_tips,
  placement_tips = excluded.placement_tips,
  references = excluded.references,
  updated_at = now();


insert into public.encyclopedia_entries (
  id,
  type,
  name,
  scientific_name,
  genus,
  category_code,
  category_name,
  risk_level,
  season,
  host_range,
  summary,
  morphology,
  symptoms,
  image_url,
  control_tips,
  placement_tips,
  references
)
values
  (
    'disease-phytophthora-infestans-tomato',
    'disease',
    '番茄晚疫病',
    'Phytophthora infestans',
    'Phytophthora',
    'oomycete',
    '卵菌病害',
    'high',
    '保护地秋冬、露地秋季（9–11月）',
    '番茄、马铃薯及茄科野生植物',
    '番茄晚疫病由致病疫霉引起，在18-22℃与持续高湿条件下可快速暴发，叶、茎、果均可受害。',
    '病原为致病疫霉（Phytophthora infestans），属卵菌病害，常在叶背产生白色霉层。',
    '叶片先见暗绿色水渍状不规则病斑，湿度高时叶背生白霉；茎秆褐色凹陷条斑，青果出现油渍状后转黑褐硬斑。',
    '/images/encyclopedia/doc/doc-disease-01.png',
    '["与非茄科轮作3年", "高垄覆膜并采用滴灌控湿", "初发期轮换使用氟啶胺、氰霜唑、精甲霜灵·锰锌等药剂"]'::jsonb,
    '["保护地加强通风降湿", "雨后及时清除病叶病果", "避免植株郁闭和长时间叶面结露"]'::jsonb,
    '["https://www.vegetables.cornell.edu/crops/tomatoes/late-blight/", "https://ipm.ucanr.edu/PMG/GARDEN/VEGES/DISEASES/lateblight.html", "https://www.fao.org/plant-health/en/", "https://www.natesc.org.cn/", "http://www.moa.gov.cn/"]'::jsonb
  ),
  (
    'disease-erysiphe-cichoracearum-cucumber',
    'disease',
    '黄瓜白粉病',
    'Erysiphe cichoracearum',
    'Erysiphe',
    'powdery',
    '白粉病类',
    'high',
    '保护地春秋季（4–6月、9–10月）',
    '黄瓜、甜瓜、南瓜及部分茄科作物',
    '黄瓜白粉病在保护地春秋季高发，昼夜温差大且夜间结露时流行快，主要危害叶片。',
    '主要病原为白粉菌（Erysiphe cichoracearum 等），初期可见白色粉点并迅速扩展。',
    '叶面与叶背出现白色粉斑，后期灰白并产生黑色小点（闭囊壳），重病叶片枯黄发脆。',
    '/images/encyclopedia/doc/doc-disease-02.png',
    '["优先选用抗病品种", "及时摘除病叶老叶并加强通风", "初发期交替使用醚菌酯、戊唑醇、吡唑醚菌酯等药剂"]'::jsonb,
    '["控制棚内湿度与结露时长", "避免高温时段喷药", "增施磷钾肥提高抗性"]'::jsonb,
    '["https://extension.usu.edu/vegetableguide/cucurbits/powdery-mildew", "https://www.apsnet.org/edcenter/disimpactmngmnt/topc/Pages/default.aspx", "https://www.fao.org/plant-health/en/", "https://www.natesc.org.cn/", "http://www.moa.gov.cn/"]'::jsonb
  ),
  (
    'disease-xanthomonas-citri-canker',
    'disease',
    '柑橘溃疡病',
    'Xanthomonas citri subsp. citri',
    'Xanthomonas',
    'bacterial',
    '细菌性病害',
    'high',
    '春梢（4–5月）、夏梢（6–7月）、秋梢（8–9月）生长期',
    '柑橘属（甜橙、脐橙、酸橙最感病，宽皮柑橘次之）',
    '柑橘溃疡病由黄单胞菌引起，风雨和潜叶蛾造成伤口后更易侵染，属高风险细菌性病害。',
    '病斑多为隆起木栓化，中央凹陷并可开裂呈火山口状，周围常见黄色晕圈。',
    '叶片、枝梢和果实均可受害，重病时引起落叶落果并影响果实商品性与运输性。',
    '/images/encyclopedia/doc/doc-disease-03.png',
    '["严格检疫并使用无病苗木", "统一放梢并同步防治潜叶蛾", "初发期喷施噻唑锌、噻菌铜、春雷·王铜等细菌性病害药剂"]'::jsonb,
    '["台风暴雨前后加强巡查", "病株与病枝及时清除并无害化处理", "减少机械损伤和修剪伤口暴露"]'::jsonb,
    '["https://direct.aphis.usda.gov/plant-pests-diseases/citrus-diseases/citrus-canker", "https://www.fao.org/plant-health/en/", "https://www.natesc.org.cn/", "http://www.moa.gov.cn/"]'::jsonb
  ),
  (
    'disease-phytophthora-parasitica-eggplant',
    'disease',
    '茄子绵疫病',
    'Phytophthora parasitica',
    'Phytophthora',
    'oomycete',
    '卵菌病害',
    'high',
    '盛夏至初秋（7–9月）',
    '茄子为主，也侵染番茄、辣椒、黄瓜',
    '茄子绵疫病在盛夏高温高湿和田间积水条件下易暴发，果实成熟期最易感病。',
    '病原为寄生疫霉（Phytophthora parasitica），属卵菌类，病部湿润时常见白色棉絮状菌丝。',
    '果实先出现水渍状圆斑并迅速扩展为黄褐至暗褐软腐斑，茎叶亦可出现近圆形水渍状病斑。',
    '/images/encyclopedia/doc/doc-disease-04.png',
    '["采用高垄栽培并严防积水", "与非寄主作物轮作2-3年", "初发期交替使用烯酰吗啉、霜脲氰·锰锌等药剂"]'::jsonb,
    '["暴雨后优先排水并降低田间湿度", "及时摘除病果减少再侵染源", "工具与采后周转筐分区消毒"]'::jsonb,
    '["https://www.vegetables.cornell.edu/crops/eggplant/phytophthora-blight/", "https://ipm.ucanr.edu/PMG/GARDEN/VEGES/DISEASES/phytophrootpepper.html", "https://www.fao.org/plant-health/en/", "https://www.natesc.org.cn/", "http://www.moa.gov.cn/"]'::jsonb
  ),
  (
    'disease-puccinia-striiformis-tritici',
    'disease',
    '小麦锈病（条锈病）',
    'Puccinia striiformis f. sp. tritici',
    'Puccinia',
    'rust',
    '锈病类',
    'high',
    '春季（3–5月）温凉多雾露',
    '小麦、大麦、黑麦及禾本科杂草',
    '小麦条锈病在春季10-15℃和持续露水条件下流行快，可显著降低千粒重和产量。',
    '病原为条形柄锈菌（Puccinia striiformis f. sp. tritici），叶面形成黄色条状夏孢子堆。',
    '病叶出现成排黄橙色孢子条，后期形成黑色冬孢子堆，重病时叶片早衰干枯。',
    '/images/encyclopedia/doc/doc-disease-05.png',
    '["优先种植抗病品种", "加强田间早期监测并清除杂草寄主", "病叶率达阈值后及时喷施三唑酮、戊唑醇、氟环唑等药剂"]'::jsonb,
    '["适期晚播降低早期侵染风险", "返青至拔节期重点巡查", "发病田块机具作业后及时清洁"]'::jsonb,
    '["https://extension.usu.edu/crops/research/wheat-stripe-rust", "https://digitalcommons.usu.edu/extension_curall/989/", "https://www.fao.org/plant-health/en/", "https://www.natesc.org.cn/", "http://www.moa.gov.cn/"]'::jsonb
  ),
  (
    'disease-septoria-apiicola-celery',
    'disease',
    '芹菜斑枯病（晚疫病）',
    'Septoria apiicola',
    'Septoria',
    'fungalLeafSpot',
    '真菌性斑点病',
    'medium',
    '秋季露地与保护地（9–11月）',
    '芹菜、根芹菜等伞形科蔬菜',
    '芹菜斑枯病由 Septoria apiicola 引起，秋季高湿和长时间结露条件下易加重。',
    '病斑中央灰白、边缘深褐，病斑上散生黑色小点（分生孢子器）是典型识别特征。',
    '叶片先现淡褐色油渍状小斑，后扩展为近圆斑，严重时叶片干枯脱落并影响商品质量。',
    '/images/encyclopedia/doc/doc-disease-06.png',
    '["种子温汤浸种消毒", "轮作2年以上并清理病残体", "初发期喷施代森锰锌、苯醚甲环唑、吡唑醚菌酯"]'::jsonb,
    '["保护地加强通风降湿", "降低夜间结露时间", "采收与修剪工具分区管理"]'::jsonb,
    '["https://pnwhandbooks.org/plantdisease/host-disease/celery-apium-graveolens-var-dulce-late-blight-septoria-leaf-blight", "https://www.apsnet.org/edcenter/disimpactmngmnt/topc/Pages/default.aspx", "https://www.fao.org/plant-health/en/", "https://www.natesc.org.cn/", "http://www.moa.gov.cn/"]'::jsonb
  ),
  (
    'disease-rhizoctonia-solani-rice-sheath-blight',
    'disease',
    '水稻纹枯病',
    'Rhizoctonia solani',
    'Rhizoctonia',
    'blight',
    '枯斑与疫病类',
    'high',
    '分蘖盛期至孕穗抽穗期（6–8月）',
    '水稻、玉米、小麦及其他禾本科作物',
    '水稻纹枯病在分蘖至孕穗期高温高湿条件下流行快，严重时造成叶鞘和叶片大片枯死。',
    '病原为立枯丝核菌（Rhizoctonia solani），病部潮湿时可见白色蛛丝状菌丝，后期形成褐色菌核。',
    '近水面叶鞘先现暗绿色水渍状斑，后扩展为云纹状大斑；重病时叶片早衰并影响灌浆。',
    '/images/encyclopedia/doc-2026/doc-disease-21.jpg',
    '["分蘖末期晒田控湿，避免长期深水灌溉", "平衡施肥并控制氮肥用量", "病丛率上升时及时轮换使用井冈霉素A、噻呋酰胺等药剂"]'::jsonb,
    '["秧田和本田分区巡查并记录病丛率", "雨后及时排水，降低田间湿度", "收获后清理病残体与菌核，减少来年初侵染源"]'::jsonb,
    '["https://www.fao.org/plant-health/en/", "https://www.apsnet.org/edcenter/disimpactmngmnt/topc/Pages/default.aspx", "https://www.natesc.org.cn/", "http://www.moa.gov.cn/"]'::jsonb
  ),
  (
    'disease-alternaria-solani-potato-early-blight',
    'disease',
    '马铃薯早疫病',
    'Alternaria solani',
    'Alternaria',
    'blight',
    '枯斑与疫病类',
    'high',
    '夏季（7–8月）高温高湿期',
    '马铃薯、番茄及茄科作物',
    '马铃薯早疫病在夏季高温高湿与植株衰弱条件下发生加重，叶片出现典型同心轮纹病斑。',
    '病原为茄链格孢（Alternaria solani），属真菌性病害，常见靶心状轮纹病斑。',
    '叶片初现黑褐色小斑，扩大后形成圆形至近圆形轮纹斑并伴黄色晕圈；块茎可见暗褐色凹陷干腐斑。',
    '/images/encyclopedia/doc-2026/doc-disease-22.jpg',
    '["与非茄科作物轮作2-3年", "增施钾肥提高植株抗性", "初发期轮换使用代森锰锌、吡唑醚菌酯、苯醚甲环唑"]'::jsonb,
    '["雨后优先清除病叶病株，减少田间菌源", "密植地块及时整枝通风", "采后彻底清园并妥善处理病残体"]'::jsonb,
    '["https://www.fao.org/plant-health/en/", "https://www.apsnet.org/edcenter/disimpactmngmnt/topc/Pages/default.aspx", "https://www.natesc.org.cn/", "http://www.moa.gov.cn/"]'::jsonb
  ),
  (
    'disease-colletotrichum-capsici-pepper-anthracnose',
    'disease',
    '辣椒炭疽病',
    'Colletotrichum capsici',
    'Colletotrichum',
    'fungalLeafSpot',
    '真菌性斑点病',
    'high',
    '盛夏至初秋（7–9月）',
    '辣椒、茄子、番茄等茄科蔬菜',
    '辣椒炭疽病在盛夏到初秋多雨高湿条件下流行迅速，果实近成熟期最易受害。',
    '病原主要为 Colletotrichum capsici 和 C. gloeosporioides，病斑湿润时常见橙红色黏质孢子团。',
    '果面形成圆形至不规则凹陷斑，颜色由褐色逐渐加深；叶片病斑中央灰白、边缘褐色并可能穿孔。',
    '/images/encyclopedia/doc-2026/doc-disease-23.jpg',
    '["种子温水浸种并进行消毒处理", "采用高垄栽培和滴灌降低叶面湿度", "病果病叶及时清除并轮换使用咪鲜胺、苯醚甲环唑、代森锰锌"]'::jsonb,
    '["雨季加强果实巡查，及时摘除病果", "减少采收和整枝时机械伤口", "通风差地块优先进行疏枝处理"]'::jsonb,
    '["https://www.fao.org/plant-health/en/", "https://www.apsnet.org/edcenter/disimpactmngmnt/topc/Pages/default.aspx", "https://www.natesc.org.cn/", "http://www.moa.gov.cn/"]'::jsonb
  ),
  (
    'disease-pseudoperonospora-cubensis-cucumber-downy',
    'disease',
    '黄瓜霜霉病',
    'Pseudoperonospora cubensis',
    'Pseudoperonospora',
    'downy',
    '霜霉病类',
    'high',
    '春秋季及露地多雨期',
    '黄瓜、甜瓜、南瓜及丝瓜等葫芦科作物',
    '黄瓜霜霉病在春秋保护地及露地多雨期高发，叶背霜状霉层是关键识别特征。',
    '病原为古巴假霜霉（Pseudoperonospora cubensis），属卵菌，低温高湿条件下侵染速度快。',
    '叶面先现淡黄色褪绿斑，后形成黄褐色不规则病斑；对应叶背可见紫灰至黑色霜状霉层。',
    '/images/encyclopedia/doc-2026/doc-disease-24.jpg',
    '["优先选用抗病品种并控制种植密度", "温室加强通风降湿，减少夜间结露", "初发期轮换使用烯酰吗啉、霜霉威盐酸盐、氟噻唑吡乙酮"]'::jsonb,
    '["持续降雨后增加巡查频次", "病叶及时清除并带出园区", "灌溉优先滴灌，避免长时间叶面潮湿"]'::jsonb,
    '["https://www.fao.org/plant-health/en/", "https://www.apsnet.org/edcenter/disimpactmngmnt/topc/Pages/default.aspx", "https://www.natesc.org.cn/", "http://www.moa.gov.cn/"]'::jsonb
  ),
  (
    'disease-plasmopara-viticola-grape-downy-doc',
    'disease',
    '葡萄霜霉病',
    'Plasmopara viticola',
    'Plasmopara',
    'downy',
    '霜霉病类',
    'high',
    '夏季至初秋（6–8月）连阴雨期',
    '葡萄（各品种均可感病）',
    '葡萄霜霉病在夏季至初秋连阴雨和高湿条件下扩散快，叶背霜霉层与幼果失水硬化较典型。',
    '病原为葡萄生单轴霉（Plasmopara viticola），属卵菌病害，主要侵染叶片、新梢与幼果。',
    '叶片正面出现淡黄色多角形病斑，背面对应处生白色霜层；幼果感病后易硬化、畸形并脱落。',
    '/images/encyclopedia/doc-2026/doc-disease-25.jpg',
    '["冬季清园并销毁病叶病梢", "生长期及时整枝摘心改善通风透光", "发病前后轮换使用代森锰锌、烯酰吗啉、霜脲氰等药剂"]'::jsonb,
    '["低洼园区优先排水并降低空气湿度", "雨后重点巡查新梢与幼果", "病残体集中处理，避免园内堆放"]'::jsonb,
    '["https://www.fao.org/plant-health/en/", "https://www.apsnet.org/edcenter/disimpactmngmnt/topc/Pages/default.aspx", "https://www.natesc.org.cn/", "http://www.moa.gov.cn/"]'::jsonb
  ),
  (
    'disease-erwinia-carotovora-cabbage-soft-rot',
    'disease',
    '白菜软腐病',
    'Erwinia carotovora subsp. carotovora',
    'Erwinia',
    'bacterial',
    '细菌性病害',
    'high',
    '秋季结球期（9–10月）',
    '白菜、甘蓝、萝卜及部分茄科作物',
    '白菜软腐病在结球期高温高湿和伤口较多时发病重，病组织软烂并伴随明显异味。',
    '病原为 Erwinia carotovora subsp. carotovora（细菌），多从叶柄基部或虫伤口侵入。',
    '病部初期呈水渍状半透明，后转灰褐色软腐并有臭味；结球白菜心叶腐烂，外叶萎蔫下垂。',
    '/images/encyclopedia/doc-2026/doc-disease-26.png',
    '["高垄栽培并防止田间积水", "避免连作并同步防治菜青虫、跳甲等害虫", "初发期喷施噻唑锌、噻菌铜、农用链霉素并及时拔除病株"]'::jsonb,
    '["雨后先排水再进行病株清理", "病穴撒施生石灰并隔离管理", "采收工具分区使用并定期消毒"]'::jsonb,
    '["https://www.fao.org/plant-health/en/", "https://www.apsnet.org/edcenter/disimpactmngmnt/topc/Pages/default.aspx", "https://www.natesc.org.cn/", "http://www.moa.gov.cn/"]'::jsonb
  )
on conflict (id) do update
set
  type = excluded.type,
  name = excluded.name,
  scientific_name = excluded.scientific_name,
  genus = excluded.genus,
  category_code = excluded.category_code,
  category_name = excluded.category_name,
  risk_level = excluded.risk_level,
  season = excluded.season,
  host_range = excluded.host_range,
  summary = excluded.summary,
  morphology = excluded.morphology,
  symptoms = excluded.symptoms,
  image_url = excluded.image_url,
  control_tips = excluded.control_tips,
  placement_tips = excluded.placement_tips,
  references = excluded.references,
  updated_at = now();
insert into public.community_posts (
  id,
  title,
  content,
  markdown,
  image_url,
  status,
  author_name,
  owner_account,
  likes,
  mentions,
  topics
)
values
  (
    '11111111-1111-1111-1111-111111111111',
    '龟背竹叶片出现褐色斑点，怎么处理？',
    '最近两周叶片边缘有褐斑，还在扩大，求助判断是病害还是浇水问题。',
    '最近两周叶片边缘有褐斑，还在扩大，求助判断是病害还是浇水问题。',
    'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?auto=format&fit=crop&w=1200&q=80',
    'open',
    'Yuki_Plants',
    null,
    45,
    '[]'::jsonb,
    '["病害", "龟背竹"]'::jsonb
  )
on conflict (id) do update
set
  title = excluded.title,
  content = excluded.content,
  markdown = excluded.markdown,
  image_url = excluded.image_url,
  status = excluded.status,
  author_name = excluded.author_name,
  likes = excluded.likes,
  topics = excluded.topics,
  updated_at = now();

insert into public.community_answers (
  id,
  post_id,
  author_name,
  content,
  markdown,
  image_url,
  role,
  reply_to_floor,
  floor,
  annotations
)
values
  (
    '22222222-2222-2222-2222-222222222222',
    '11111111-1111-1111-1111-111111111111',
    '植保社团-小林',
    '先剪掉重病叶，检查是否长期积水。可配合铜制剂低浓度喷施。',
    '先剪掉重病叶，检查是否长期积水。可配合铜制剂低浓度喷施。',
    null,
    'answer',
    null,
    2,
    '[]'::jsonb
  )
on conflict (id) do update
set
  content = excluded.content,
  markdown = excluded.markdown,
  role = excluded.role,
  floor = excluded.floor,
  updated_at = now();

insert into public.spirit_sessions (
  id,
  identify,
  generation,
  messages,
  draft_count,
  last_draft_at
)
values
  (
    '33333333-3333-4333-8333-333333333333',
    '{"name":"瓢虫","scientificName":"Coccinella septempunctata","keywords":["益虫","蚜虫天敌"],"summary":"用于演示灵化会话持久化。","cover":"https://example.com/ladybug.png","encyclopediaId":"insect-coccinella-septempunctata"}'::jsonb,
    '{"taskId":"44444444-4444-4444-8444-444444444444","status":"succeeded","imageUrl":"https://example.com/generated-ladybug.png","promptId":"prompt-demo","durationMs":1820,"presetId":"campus_anime","workflowId":"default"}'::jsonb,
    '[{"id":"msg-1","role":"spirit","text":"你好，我是瓢虫精灵。"},{"id":"msg-2","role":"user","text":"请给我防治建议。"}]'::jsonb,
    1,
    now()
  )
on conflict (id) do update
set
  identify = excluded.identify,
  generation = excluded.generation,
  messages = excluded.messages,
  draft_count = excluded.draft_count,
  last_draft_at = excluded.last_draft_at,
  updated_at = now();

insert into public.spirit_community_drafts (
  id,
  session_id,
  title,
  content,
  markdown,
  image_url,
  mentions,
  topics,
  status
)
values
  (
    '55555555-5555-4555-8555-555555555555',
    '33333333-3333-4333-8333-333333333333',
    '【灵化记录】瓢虫识别与防治建议',
    '识别对象：瓢虫（Coccinella septempunctata）\n关键词：益虫 / 蚜虫天敌\n识别摘要：用于演示灵化会话持久化。\n生图任务：succeeded，耗时 1820ms\n生图结果：https://example.com/generated-ladybug.png',
    '识别对象：瓢虫（Coccinella septempunctata）\n关键词：益虫 / 蚜虫天敌\n识别摘要：用于演示灵化会话持久化。\n生图任务：succeeded，耗时 1820ms\n生图结果：https://example.com/generated-ladybug.png',
    'https://example.com/generated-ladybug.png',
    '[]'::jsonb,
    '["灵化角色","校园植保","益虫"]'::jsonb,
    'draft'
  )
on conflict (id) do update
set
  title = excluded.title,
  content = excluded.content,
  markdown = excluded.markdown,
  image_url = excluded.image_url,
  mentions = excluded.mentions,
  topics = excluded.topics,
  status = excluded.status,
  updated_at = now();
